/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 vision_llm_agent/interface/public/assets/models/court.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Court({ props, nodes, materials }) {
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.AmericanFlag_BasketballBaseShader_0.geometry}
        material={materials.BasketballBaseShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.BackBoardTrim_GrayMetalShader_0.geometry}
        material={materials.GrayMetalShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.BackBoardTrims_WhiteBackboardShader_0.geometry}
        material={materials.WhiteBackboardShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.BlackMetal_BlackMetalShader_0.geometry}
        material={materials.BlackMetalShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Glass_BasketballHoop_GlassShader_0.geometry}
        material={materials.BasketballHoop_GlassShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Net_RopeShader_0.geometry}
        material={materials.RopeShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Ring_OrangeMetalShader_0.geometry}
        material={materials.OrangeMetalShader}
        position={[2, 0.474, 10.7]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Bolts_GalvanizedMetalShader_0.geometry}
        material={materials.GalvanizedMetalShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.BulbConnectors_BulbConnectorsShader_0.geometry}
        material={materials.BulbConnectorsShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Bulbs_LightShader_0.geometry}
        material={materials.LightShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Court_WhiteTapeShader_0.geometry}
        material={materials.WhiteBackboardShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Doors_LockerHandleShader_0.geometry}
        material={materials.LockerHandleShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.DoorTrims_PlasterShader_0.geometry}
        material={materials.PlasterShader}
        position={[-13.44, 4.08, -1.68]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.EntranceDoors1_GlassShader_0.geometry}
        material={materials.GlassShader}
        position={[0.84, 2.509, 17.236]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.EntranceDoors1_WoodFineShader_0.geometry}
        material={materials.WoodFineShader}
        position={[0.84, 2.509, 17.236]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.GymFloor_ParquetShader_0.geometry}
        material={materials.ParquetShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.LevelFloor_FloorsShader_0.geometry}
        material={materials.FloorsShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Lights_PolishedMetalShader_0.geometry}
        material={materials.PolishedMetalShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Locker1_BlueLockerShader_0.geometry}
        material={materials.BlueLockerShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Locker1_SilverLockerShader_0.geometry}
        material={materials.SilverLockerShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.PlatedDoors_MetalPlatesShader_0.geometry}
        material={materials.MetalPlatesShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Railings_ConcreteBareShader_0.geometry}
        material={materials.ConcreteBareShader}
        position={[-13.68, 0, 17.52]}
        scale={0.02}
      />
    </group>
  );
}

useGLTF.preload('/public/assets/models/court.glb');
