/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 vision_llm_agent/interface/public/assets/models/lobby.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Lobby({ props, nodes, materials }) {
  return (
    <group {...props} dispose={null}>
      <group
        position={[6.184, 0.313, 11.351]}
        rotation={[-Math.PI, 1.195, -Math.PI]}
        scale={[3.117, 0.063, 0.125]}
      >
        <mesh geometry={nodes.Cube013.geometry} material={materials.stairs} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.glass} />
      </group>
      <group position={[14.183, 1, -2]} scale={[0.9, 1, 0.1]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.pillar} />
      </group>
      <group position={[1.183, 0, -1]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.floor} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.wall} />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials.ceiling}
        />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials.glass} />
      </group>
      <group position={[5.183, 0, 8.779]} scale={[5, 0.5, 2.5]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.wall} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.glass} />
      </group>
      <mesh
        geometry={nodes.columns.geometry}
        material={materials.pillar}
        position={[16.183, 1, 12.898]}
        scale={[0.25, 1, 0.23]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.cabinet}
        position={[8.601, 0.53, 10.688]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.281, 0.53, 2.168]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.cabinet}
        position={[8.915, 0.53, -7.575]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.281, 0.53, 2.168]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.cabinet}
        position={[2.733, 0.53, -5.225]}
        rotation={[-Math.PI, 0.328, -Math.PI]}
        scale={[0.281, 0.53, 2.168]}
      />
    </group>
  );
}

useGLTF.preload('assets/models/lobby.glb');
