/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 vision_llm_agent/interface/public/assets/models/street.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { EdgesGeometry, LineBasicMaterial } from 'three';

export function Street({ props, nodes, materials }) {
  const { outline } = props;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.trees.geometry}
        material={materials.Tree}
        position={[-19.633, 5.317, -8.012]}
        scale={[3.519, 2.918, 3.519]}
      />
      <mesh
        geometry={nodes.ppl.geometry}
        material={materials.person}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={100}
      />
      {/* People Edges */}
      {outline && (
        <lineSegments
          geometry={new EdgesGeometry(nodes.ppl.geometry)}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
          material={new LineBasicMaterial({ color: 'black', name: 'person' })}
        />
      )}
      <mesh
        geometry={nodes.buildings.geometry}
        material={materials.building}
        position={[33.856, 6.562, 19.813]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[9.397, 6.562, 9.202]}
      />
      {/* Buildings Edges */}
      {outline && (
        <lineSegments
          geometry={new EdgesGeometry(nodes.buildings.geometry)}
          position={[33.856, 6.562, 19.813]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[9.397, 6.562, 9.202]}
          material={new LineBasicMaterial({ color: 'black', name: 'building' })}
        />
      )}

      <group scale={[50, 1, 5]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.road} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.sidewalk} />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={materials.sign}
        position={[-68.558, 6.563, 52.397]}
        rotation={[Math.PI / 2, 0, 2.116]}
        scale={[3.965, 1.058, 3.965]}
      />
      {/* Text Edges */}
      {outline && (
        <lineSegments
          geometry={new EdgesGeometry(nodes.Text.geometry)}
          position={[-68.558, 6.563, 52.397]}
          rotation={[Math.PI / 2, 0, 2.116]}
          scale={[3.965, 1.058, 3.965]}
          material={
            new LineBasicMaterial({ color: 'black', name: 'subway station' })
          }
        />
      )}
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['subway station']}
        position={[-68.863, 5.28, 58.617]}
        rotation={[0, -0.56, 0]}
        scale={[2.865, 5.28, 7.33]}
      />
      {/* Station Edges */}
      {outline && (
        <lineSegments
          geometry={new EdgesGeometry(nodes.Cube001.geometry)}
          position={[-68.863, 5.28, 58.617]}
          rotation={[0, -0.56, 0]}
          scale={[2.865, 5.28, 7.33]}
          material={
            new LineBasicMaterial({ color: 'black', name: 'subway station' })
          }
        />
      )}
    </group>
  );
}

useGLTF.preload('assets/models/street.glb');
